# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DailyDoggos

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  run:
    name: Run Cron Job
    runs-on: ubuntu-latest
    env:
      HEALTHCHECKS_URL: ${{ secrets.HEALTHCHECKS_URL }}
      TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: node index.js
